### ISSUE TITLE
Network policy needed

### ISSUE THREAD

**Issue by molund** [bcgov/crunchy-postgres#59]
If you are using this on a brand new OpenShift namespace, you need to create a network policy to allow your pods to talk to each other.  
This should be documented in the README. 

e.g.
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name:  allow-same-namespace
  namespace: abc123-dev
spec:
  podSelector: {}
  ingress:
    - from:
        - podSelector: {}
  policyTypes:
    - Ingress
```
